# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Stocked' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stocked

	

  target 'StockedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockedUITests' do
    # Pods for testing
  end

end
